### ISSUE TITLE
How long it takes for desktop app to start cause I see "Replicating" after using my key.

### ISSUE THREAD

**Issue by geolffreym** [ZorrillosDev/watchit-gateway#26]
> How long it takes for desktop app to start cause I see "Replicating" after using my key.

In your case it could take a little time if you are behind a NAT, it is likely that to distribute your content you need to help your node with a circuit relay or peering.peers.. please try this:

1) `
docker-compose exec watchit_ipfs ipfs config Peering.Peers '
[
  { "ID": "QmSHSTNyKJ1EGVVKj7dKZFmxj9FaBfE7S23MNTj1Jwungg", "Addrs": ["/ip4/34.209.228.155/tcp/4001"] },
  { "ID": "12D3KooWQw3vx2E4FKpL9GHC9BpFya1MXVUFEVBAQVhMDkreCqwF", "Addrs": ["/ip4/185.215.224.79/tcp/4001"] },
  { "ID": "12D3KooWD4Z47R1pnzTxCVQAiTKTHasWU2xTAcffyC38BNKM68yw", "Addrs": ["/ip4/185.215.227.40/tcp/4001"] },
  { "ID": "QmbPFTECrXd7o2HS2jWAJ2CyAckv3Z5SFy8gnEHKxxH52g", "Addrs": ["/ip4/144.172.69.157/tcp/4001"] }
]' --json` 

2) `docker-compose stop && docker-compose up` or just `docker-compose restart`
 

or in root dir just run `sh src/bash/init_ipfs.sh && docker-compose restart`

_Originally posted by @geolffreym in https://github.com/ZorrillosDev/watchit-gateway/issues/25#issuecomment-809728182_

**Comment by kodxana** [comment]
I have IPFS port open so NAT should not be a issue do I also need expose OrbisDB?

**Comment by geolffreym** [comment]
> I have IPFS port open so NAT should not be a issue do I also need expose OrbisDB?

`Peering.Peers` could help to orbit too since orbitdb use IPFS. This list of peers  are used by the app, please add it to your gateway to help the app found you

**Comment by kodxana** [comment]
Still no luck :/

**Comment by geolffreym** [comment]
@all-contributors please add @phillmac  for code, userTesting, research, ideas, infra

**Comment by geolffreym** [comment]
@all-contributors please add @aphelionz  for code, ideas

**Comment by geolffreym** [comment]
@kodxana any news about this issue?

**Comment by kodxana** [comment]
Still nothing works so I have up.

**Comment by geolffreym** [comment]
Are you having issues finding peers right? @kodxana .. can you bring me your IPFS-gateway conf please?

**Comment by kodxana** [comment]
> Are you having issues finding peers right? @kodxana .. can you bring me your IPFS-gateway conf please?

Nope I'm nonnected to about 950 peers right now

**Comment by phillmac** [comment]
Total swarm peers =/= peers with the watchit DB info.
There's only about 5 - 10 peers with the db in the entire swarm, so unless
you connect specifically to those peers, you will not get a copy of the db.
The workaround is to use the new `Peering.Peers` config option in ipfs to
try to maintain a connection to the worker nodes that are set up to make
the db available to the swarm.

**Comment by EchedeyLR** [comment]
Are these peers acting more like "TURN" servers or "STUN"?

I mean, if the bandwidth is wasted is increased proportionally to the content watched in through the gateway of the other person or it just helps to find.

**Comment by phillmac** [comment]
Neither. The worker nodes are full replicas, that is they store the db contents.
The db is only a list of metadata however, not the video content.

**Comment by geolffreym** [comment]
@kodxana any news about this issue?
