### ISSUE TITLE
Error while running docker compose

### ISSUE THREAD

**Issue by nickdex** [ZorrillosDev/watchit-gateway#40]
OS - PopOs (Ubuntu 20.10)

When I ran `docker-compose up` command I got following error
```
WARNING: The RUNTIME_DIRECTORY variable is not set. Defaulting to a blank string.
WARNING: The MONITOR_CID variable is not set. Defaulting to a blank string.
watchit-gateway_watchit_certbot_1 is up-to-date
Starting watchit-gateway_watchit_ipfs_1 ... 
Starting watchit-gateway_watchit_ipfs_1 ... done
Creating watchit-gateway_watchit_reverse_proxy_1 ... done
Creating watchit-gateway_watchit_orbitdb_api_1   ... done
Creating watchit_migrator                        ... error
Creating watchit-gateway_watchit_db_monitor_1    ... 

ERROR: for watchit_migrator  Cannot create container for service watchit_migrator: create .: volume name Creating watchit-gateway_watchit_db_monitor_1    ... done

ERROR: for watchit_migrator  Cannot create container for service watchit_migrator: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.
```

**Comment by geolffreym** [comment]
Hi @nickdex thanks for submit an issue. Could u try rename ‘.env.example’ to ‘.env’ and define your conf there?

**Comment by nickdex** [comment]
This is what I see after I added an .env manually with IPFS_DATA set to my local ipfs store. 
Do I need to add anything more to the .env file?

**Comment by geolffreym** [comment]
Hi!! Yeah, some extra var are needed. Please check original env.example https://github.com/ZorrillosDev/watchit-gateway/blob/v0.1.0/.env.example

**Comment by geolffreym** [comment]
Hi @nickdex any update about this issue?

**Comment by nickdex** [comment]
@geolffreym Hey, I didn't get a chance to check  it out and doesn't look like I'll get around to it for couple of weeks. Do you want to mark it stale or close it for time being or something else?

**Comment by geolffreym** [comment]
Hmm!! please let us know if this isse persist. We are happy to help :)
